version: "3.8"

services:
  web:
    build: .
    container_name: autodetecter_app
    ports:
      - "8000:8000"
    volumes:
      - ./dataset:/app/dataset
      - ./bias_pipeline_output:/app/bias_pipeline_output
    env_file:
      - .env
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped
